---
title: "Alternative DE methods on CD8+ T Cell CROP-seq Data"
subtitle: "-- In-house scripts"
author: "Yifan Zhou (zhouyf@uchicago.edu)"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float: true
---

```{r setup, include=FALSE}
requireNamespace("pander", quietly = TRUE)
# set default chunk output
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      comment = NA,
                      tidy = FALSE,
                      fig.width = 7,
                      fig.height = 5,
                      fig.align = "center",
                      results = "asis")

# formatting of pander tables
pander::panderOptions('knitr.auto.asis', FALSE)
pander::panderOptions("table.split.table", Inf)
```

This tutorial describes how to run alternative differential expression (DE) methods on CD8+ T Cell CROP-seq data. **All analyses are limited to the stimulated group only.** All file paths here are relative to this working directory: `/project2/xinhe/yifan/Factor_analysis/Stimulated_T_Cells/`.

## DESeq2

### R script

Location: `run_deseq.all_by_stim.R`;

Command line usage example:

```
Rscript run_deseq.all_by_stim.R --out_folder=processed_data/DESeq2/all_by_stim_negctrl/ --marker=ARID1A --NTC_only=TRUE --permute=FALSE
```

`marker`: the gRNA perturbation condition to test the differential effects,  
`NTC_only`: whether to compare with only nontargeting control cells or all cells 
in other conditions.

### Run jobs at scale

Edit the Python script `submit_DE_jobs_in_batches.py`, which can submit sbatch jobs for all gRNA targets.

Make sure to modify the sbatch script defined in `make_DEG_sbatch()` and loop over all conditions.

To submit jobs, run the edited script: `./submit_DE_jobs_in_batches.py`.

### Output

Each gRNA condition vs negative control: `processed_data/DESeq2/all_by_stim_negctrl/`;

Each gRNA condition vs the rest of cells: `processed_data/DESeq2/all_by_stim_dev_6k/`;

## MAST

Location: `run_MASTcpmDetRate.all_by_stim.R`;

Command line usage example:

```
Rscript run_MASTcpmDetRate.all_by_stim.R --out_folder=processed_data/MAST/all_by_stim_negctrl/ --marker=ARID1A --NTC_only=TRUE --permute=FALSE
```

`marker`: the gRNA perturbation condition to test the differential effects,  
`NTC_only`: whether to compare with only nontargeting control cells or all cells 
in other conditions.

### Run jobs at scale

Edit the Python script `submit_DE_jobs_in_batches.py`, which can submit sbatch jobs for all gRNA targets.

Make sure to modify the sbatch script defined in `make_DEG_sbatch()` and loop over all conditions.

To submit jobs, run the edited script: `./submit_DE_jobs_in_batches.py`.

### Output

Each gRNA condition vs negative control: `processed_data/MAST/all_by_stim_negctrl/`;

Each gRNA condition vs the rest of cells: `processed_data/MAST/all_by_stim_dev_6k/`;

## scMAGeCK

### R script

Location: `scmageck/run_scmageck.R`;

Command line usage example (works on all gRNA conditions at once):

```
Rscript scmageck/run_scmageck.R --permute=FALSE
```

### Output

Each gRNA condition vs negative control among stimulated cells: `scmageck/scmageck_lr.TCells_stim.dev_res_top_6k.rds`.

Each gRNA condition vs negative control among unstimulated cells:`scmageck_lr.TCells_unstim.dev_res_top_6k.rds`.
