---
title: "Guided Sparse Factor Analysis Project"
subtitle: "-- In-house scripts"
author: "Yifan Zhou (zhouyf@uchicago.edu)"
output:
  html_document:
    number_sections: no
    toc: yes
    toc_float: true
---

## Simulation study

* [Simulation and GSFA run](run_gsfa_simulations.html);  
* Normal scenario results  
* Count-based scenario results

## LUHMES neural progenitor CROP-seq study

* [Preprocessing of LUHMES CROP-seq data](preprocess_LUHMES.html);  
* [GSFA application on processed CROP-seq data](run_gsfa_LUHMES.html);  
* [GSFA result interpretation](interpret_gsfa_LUHMES.html);  
* [Alternative differential expression methods](DE_alternatives_LUHMES.html);

## Primary human CD8+ T cell CROP-seq study

* [Preprocessing of T cell CROP-seq data](preprocess_TCells.html);  
* [GSFA application on processed CROP-seq data](run_gsfa_TCells.html);  
* [GSFA result interpretation](interpret_gsfa_TCells.html);
* [Alternative differential expression methods](DE_alternatives_TCells.html);
